apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    name: openshift-logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  labels:
    name: openshift-operators-redhat
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  labels:
    name: openshift-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    name: grafana