{
 "title": "vLLM Logging",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d" }
  ]
 },
 "panels": [
  {
   "title": "Tokens Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (user, model) (\r\n  sum_over_time(\r\n    { log_type=\"application\", k8s_container_name=~\"kserve-container\" } |= `chatcmpl`\r\n      | json\r\n      | line_format \"{{.message}}\" |~ \"OpenAI Usage\"\r\n      | regexp \"chatcmpl-(?<request_id>.*?),\" | regexp \"Model: (?<model>.*?),\" | regexp \"User: (?<user>.*?),\" | regexp \"Prompt: (?<prompt>.*?),\" | regexp \"Completion: (?<completion>.*?),\" | regexp \"Total: (?<total>.*?),\"\r\n      | user != \"\" and request_id != \"\"\r\n      | unwrap total\r\n    [$interval]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (user) (\r\n  count_over_time(\r\n    { log_type=\"application\", k8s_container_name=~\"kserve-container\" } |= `chatcmpl`\r\n      | json\r\n      | line_format \"{{.message}}\" |~ \"OpenAI Usage\"\r\n      | regexp \"chatcmpl-(?<request_id>.*?),\" | regexp \"Model: (?<model>.*?),\" | regexp \"User: (?<user>.*?),\" | regexp \"Prompt: (?<prompt>.*?),\" | regexp \"Completion: (?<completion>.*?),\" | regexp \"Total: (?<total>.*?),\"\r\n      | user != \"\" and request_id != \"\"\r\n    [$interval]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Tokens By User Chart",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Tokens By User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Raw Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{ log_type=\"application\", k8s_container_name=~\"kserve-container\" } |= `chatcmpl` | json | line_format \"{{.message}}\" |~ \"OpenAI Usage\" | regexp \"chatcmpl-(?<request_id>.*?),\" | regexp \"Model: (?<model>.*?),\" | regexp \"User: (?<user>.*?),\" | regexp \"Prompt: (?<prompt>.*?),\" | regexp \"Completion: (?<completion>.*?),\" | regexp \"Total: (?<total>.*?),\" | regexp \"Request: (?<request>.*?),\\\\s+Response\" | regexp \"Response: (?<response>.*?)$\""
    }
   ]
  }
 ]
}