kind: Secret
apiVersion: v1
metadata:
  name: logging-s3
  namespace: openshift-logging
stringData:
  type: s3
  access_key_secret: {{ .Values.secretAccessKey }}
  region: local
  endpoint: http://s3.openshift-storage.svc
  bucketnames: {{ .Values.defaultBucket }}
  access_key_id:  {{ .Values.accessKeyId }}